spring:
  main:
    banner-mode: off
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  lifecycle:
    timeout-per-shutdown-phase: ${GRACEFUL_SHUTDOWN_TIMEOUT:60s}
  profiles:
    active: ${PROFILE_ACTIVE:dev}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library_management
    username: root
    password: 30121998

server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful

logging:
  level:
    ROOT: INFO
    com.example.demo: ${LOGGING_LEVEL:DEBUG}
    org:
      springframework:
        boot:
          autoconfigure: ERROR

management:
  endpoints:
    web:
      exposure:
        include: "loggers"

useSwagger: ${ENABLE_SWAGGER:true}

jwt:
  secret: mysecret